eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: ${EUREKA_URL}

logging:
  file:
    name: ${LOG_PATH}/${spring.application.name}.log

server:
  port: 8080

spring:
  application:
    name: template-server

  cache:
    cache-names: ${spring.application.name}-cache
    caffeine:
      spec: maximumSize=100
    type: caffeine